---
apiVersion: v1
kind: Pod
metadata:
  name: mybroker
  labels:
    app: broker
spec:
  containers:
    - name: broker
      image: mybroker:0.1
      resources:
        limits:
          memory: 200M
          cpu: 500m
      command: ["broker"]
      args: ["10.97.11.20:9092"]
---
apiVersion: v1
kind: Service
metadata:
  name: broker
spec:
  type: LoadBalancer
  ports:
  - name: webport
    protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: broker
