---
# This is headless service.
# StatefulSet
apiVersion: v1
kind: Service
metadata:
  name: elastic
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http-port
    port: 9200
    targetPort: 9200
  - name: tcp-port
    port: 9300
    targetPort: 9300
  selector:
    app: elastic
