---
apiVersion: v1
kind: Pod
metadata:
  name: mykafka
  labels:
    app: kafka
spec:
  containers:
  - name: zookeeper
    image: confluentinc/cp-zookeeper:5.4.9
    env:
    - name: TZ
      value: "Asia/Seoul"
    - name: ZOOKEEPER_SERVER_ID
      value: "1"
    - name: ZOOKEEPER_CLIENT_PORT
      value: "2181"
    - name: ZOOKEEPER_TICK_TIME
      value: "2000"
    - name: ZOOKEEPER_INIT_LIMIT
      value: "5"
    - name: ZOOKEEPER_SYNC_LIMIT
      value: "2"
    resources:
      limits:
        memory: 1G
        cpu: "1"
  - name: kafka
    image: confluentinc/cp-kafka:5.4.9
    env:
    - name: TZ
      value: "Asia/Seoul"
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    - name: KAFKA_BROKER_ID
      value: "1"
    - name: KAFKA_ZOOKEEPER_CONNECT
      value: "localhost:2181"
    - name: KAFKA_ADVERTISED_LISTENERS
      value: "PLAINTEXT://$(POD_IP):9092,PLAINTEXT_HOST://localhost:29092"
    - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
      value: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
    - name: KAFKA_INTER_BROKER_LISTENER_NAME
      value: PLAINTEXT
    - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
      value: "1"
    - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
      value: "0"
    resources:
      limits:
        memory: 1G
        cpu: "1"

## topic is created by logstash
