# https://devocean.sk.com/blog/techBoardDetail.do?ID=164007
# https://docs.confluent.io/platform/current/installation/docker/operations/external-volumes.html

version: '2'

# volumes:
#   kafkadata:
#     external: false
      
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.4.9
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
    ports:
      - "22181:2181"
    volumes:
      - .\\zookeeper\\data:/var/lib/zookeeper/data
      - .\\zookeeper\\log:/var/lib/zookeeper/log

  kafka:
    image: confluentinc/cp-kafka:5.4.9
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    volumes:
      - .\\kafka\\data:/var/lib/kafka/data
